name: big-data
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy=1.14.3
  - scipy=1.0.0
  - autopep8=1.3.4
  - beautifulsoup4=4.6.3
  - dask=0.18.2
  - distributed=1.22.1
  - fastparquet=0.1.5
  - feather-format=0.4.0
  - findspark=1.3.0
  - graphviz=2.38.0
  - hdf5=1.10.2
  - h5py=2.8.0
  - hdfs3=0.3.0
  - ipywidgets=7.2.1
  - jupyter=1.0.0
  - jupyterlab=0.34.2
  - line_profiler=2.1.2
  - lorem=0.1.1
  - lxml=4.2.4
  - matplotlib=2.2.2
  - ncurses=6.1
  - orc=1.5.1
  - pandas=0.23.4
  - paramiko=2.4.1
  - pyarrow=0.9.0
  - python-avro=1.8.2
  - python-snappy=0.5.3
  - seaborn=0.9.0
  - xlwt=1.3.0
  - blosc=1.14.4
  - nodejs=10.4.1
  - numexpr=2.6.6
  - pytables=3.4.4
  - twisted=18.7.0
  - jupyter_nbextensions_configurator=0.4.0
  - python-graphviz=0.8.4
  - tqdm=4.24.0
  - py4j=0.10.7
  - pyspark=2.3.1
  - widgetsnbextension=3.2.1
  - rpy2=2.9.4
  - r-irkernel=0.8.12
