channels:
  - conda-forge
  - defaults
dependencies:
  - absl-py
  - astor
  - bokeh
  - c-ares
  - click
  - cloudpickle
  - cycler
  - cytoolz
  - dask
  - dask-core
  - dask-jobqueue
  - dbus
  - distributed
  - docrep
  - expat
  - fontconfig
  - freetype
  - gast
  - gettext
  - glib
  - grpcio
  - gst-plugins-base
  - gstreamer
  - h5py
  - hdf5
  - heapdict
  - icu
  - jinja2
  - jpeg
  - keras
  - keras-applications
  - keras-preprocessing
  - kiwisolver
  - libffi
  - libgfortran
  - libgfortran-ng
  - libgpuarray
  - libiconv
  - libpng
  - libprotobuf
  - libstdcxx-ng
  - libtiff
  - libuuid
  - libxcb
  - libxml2
  - locket
  - mako
  - markdown
  - markupsafe
  - matplotlib
  - matplotlib-base
  - mkl_fft
  - mkl_random
  - msgpack-python
  - ncurses
  - olefile
  - openblas
  - packaging
  - pandas
  - partd
  - patsy
  - pcre
  - pip
  - protobuf
  - psutil
  - pthread-stubs
  - pygpu
  - pyparsing
  - pyqt
  - python-dateutil
  - pytz
  - pyyaml
  - qt
  - readline
  - seaborn
  - setuptools
  - sip
  - six
  - sortedcontainers
  - sqlite
  - statsmodels
  - tblib
  - tensorboard
  - tensorflow
  - termcolor
  - theano
  - tk
  - toolchain
  - toolchain_c_linux-64
  - toolchain_cxx_linux-64
  - toolz
  - tornado
  - werkzeug
  - wheel
  - xorg-libxau
  - xorg-libxdmcp
  - xz
  - yaml
  - zict
  - zlib
  - blas
  - ca-certificates
  - certifi
  - decorator
  - imageio
  - intel-openmp
  - libgcc-ng
  - mkl
  - networkx
  - numpy
  - numpy-base
  - openssl
  - pillow
  - pywavelets
  - scikit-image
  - scikit-learn
  - scipy
  - pip:
    - msgpack
